inherit_gem:
  syntax_tree: config/rubocop.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
  - '{tmp,vendor,yard}/**/*'
  - 'test/ragel/fixtures/*'

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 80

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false
